#ifndef PROCONTHREAD_GLOBAL_H
#define PROCONTHREAD_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PROCONTHREAD_LIBRARY)
#  define PROCONTHREADSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PROCONTHREADSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PROCONTHREAD_GLOBAL_H
